### ISSUE TITLE
Hey h.mondal,I am muntasir.Where is your readme.md?

### ISSUE THREAD

**Issue by MuntasirSZN** [hrimondal/fibonacci#1]

**Comment by hrimondal** [comment]
# Here is it. You should have found it.
@MuntasirSZN 
https://github.com/hrimondal/hrimondal/blob/main/README.md

**Comment by MuntasirSZN** [comment]
> # Here is it. You should have found it.
> @MuntasirSZN https://github.com/hrimondal/hrimondal/blob/main/README.md

Noooooooooooooooooooooooooooooooooooo


The readme file for this repository,not your bio.

**Comment by hrimondal** [comment]
What should I do?
@MuntasirSZN

**Comment by MuntasirSZN** [comment]
> What should I do? @MuntasirSZN

Create a readme.md file AND commit it.

**Comment by MuntasirSZN** [comment]
> What should I do? @MuntasirSZN

Check pull requests.Merge them.
